# TODO: This file was included just for testing and needs to be removed before upstreaming to Edgex

# /*******************************************************************************
#  * Copyright 2020 Redis Labs Inc.
#  * Copyright 2020 Intel Corporation.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * @author: Andre Srinivasan, Redis Labs
#  * @author: Leonard Goodell, Intel
#  * EdgeX Foundry, Geneva, version 1.2.0
#  * added: May 14, 2020
#  *******************************************************************************/

# NOTE:  this Docker Compose file does not contain the security services - namely the API Gateway
# and Secret Store

version: '3.4'

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  Registry_Host: edgex-core-consul
  Clients_CoreData_Host: edgex-core-data
  Clients_Notifications_Host: edgex-support-notifications
  Clients_Metadata_Host: edgex-core-metadata
  Clients_Command_Host: edgex-core-command
  Clients_Scheduler_Host: edgex-support-scheduler
  Clients_RulesEngine_Host: edgex-kuiper
  Clients_VirtualDevice_Host: edgex-device-virtual
  Clients_LLRPDevice_Host: edgex-device-llrp
  Databases_Primary_Host: edgex-redis
  # Required in case old commands from previous release used.
  # Change to "true" if re-enabling logging service for remote logging
  Logging_EnableRemote: "false"
  #  Clients_Logging_Host: edgex-support-logging # un-comment if re-enabling logging service for remote logging

services:
  rfid-inventory:
    image: edgexfoundry/docker-rfid-inventory:0.0.0-dev
    ports:
      - "127.0.0.1:48086:48086"
    container_name: edgex-app-service-rfid-inventory-service
    hostname: edgex-app-service-rfid-inventory-service
    networks:
      device-llrp-go_edgex-network:
        aliases:
          - edgex-app-service-rfid-inventory-service
    environment:
      <<: *common-variables
      Service_Host: edgex-app-service-rfid-inventory-service
      Service_Port: 48086
      MessageBus_SubscribeHost_Host: edgex-core-data
      Binding_PublishTopic: events

networks:
  device-llrp-go_edgex-network:
    external: true

